language: python
dist: ubuntu

services:
  - docker

jobs:
  include:
    - stage: build
      name: "Build Docker image"
      script:
        - sudo rm /var/lib/apt/lists/lock
        - sudo rm /var/cache/apt/archives/lock
        - sudo rm /var/lib/dpkg/lock*
        - sudo dpkg --configure -a
        - sudo apt-get update
        - sudo apt-get clean
        - sudo rm -rf /var/lib/apt/lists/*
        - sudo rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true
        - sudo rm /var/lib/apt/lists/lock || true
        - sudo rm /var/lib/dpkg/lock-frontend
        - sudo apt-get update --fix-missing
        - sudo apt-get install -y apt-utils
        - sudo dpkg --configure -a
        - docker build --no-cache -t login-image:latest .
