name: python

on:

  workflow_dispatch:

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Run a one-line script
        run: echo Deploy ok!

  deploy-job:
    runs-on: ubuntu-latest
    needs: test-job
    steps:
      - name: Run a one-line script
        run: echo Hello, World!
